export const neonAuthLocalizations = {
  'zh-TW': {
    ACCOUNT: '帳戶',
    ADD_ACCOUNT: '新增帳戶',
    ALREADY_HAVE_AN_ACCOUNT: '已經有帳戶了？',
    CANCEL: '取消',
    CONFIRM_PASSWORD: '確認密碼',
    CONFIRM_PASSWORD_PLACEHOLDER: '再次輸入密碼',
    CONFIRM_PASSWORD_REQUIRED: '請再次輸入密碼',
    CONTINUE: '繼續',
    DONT_HAVE_AN_ACCOUNT: '還沒有帳戶？',
    EMAIL: '電子郵件',
    EMAIL_DESCRIPTION: '請輸入您要用來登入的電子郵件。',
    EMAIL_INSTRUCTIONS: '請輸入有效的電子郵件地址。',
    EMAIL_PLACEHOLDER: 'name@example.com',
    EMAIL_REQUIRED: '請輸入電子郵件',
    EMAIL_VERIFICATION: '請到信箱確認驗證連結。',
    FORGOT_PASSWORD: '忘記密碼',
    FORGOT_PASSWORD_ACTION: '寄送重設連結',
    FORGOT_PASSWORD_DESCRIPTION: '請輸入電子郵件以重設密碼',
    FORGOT_PASSWORD_EMAIL: '請到信箱查看密碼重設連結。',
    FORGOT_PASSWORD_LINK: '忘記密碼？',
    GO_BACK: '返回',
    IS_INVALID: '格式不正確',
    IS_REQUIRED: '為必填',
    NAME: '名稱',
    NAME_DESCRIPTION: '請輸入您的姓名或顯示名稱。',
    NAME_INSTRUCTIONS: '最多 32 個字元。',
    NAME_PLACEHOLDER: '您的名稱',
    NEW_PASSWORD: '新密碼',
    NEW_PASSWORD_PLACEHOLDER: '輸入新密碼',
    NEW_PASSWORD_REQUIRED: '請輸入新密碼',
    OR_CONTINUE_WITH: '或使用以下方式繼續',
    PASSWORD: '密碼',
    PASSWORD_PLACEHOLDER: '輸入密碼',
    PASSWORD_REQUIRED: '請輸入密碼',
    PASSWORDS_DO_NOT_MATCH: '兩次輸入的密碼不一致',
    PASSWORD_TOO_SHORT: '密碼太短',
    PASSWORD_TOO_LONG: '密碼太長',
    INVALID_EMAIL: '電子郵件格式不正確',
    INVALID_PASSWORD: '密碼格式不正確',
    INVALID_EMAIL_OR_PASSWORD: '電子郵件或密碼不正確',
    REMEMBER_ME: '記住我',
    REQUEST_FAILED: '請求失敗，請稍後再試',
    RESET_PASSWORD: '重設密碼',
    RESET_PASSWORD_ACTION: '儲存新密碼',
    RESET_PASSWORD_DESCRIPTION: '請在下方輸入新密碼',
    RESET_PASSWORD_SUCCESS: '密碼已成功重設',
    SAVE: '儲存',
    SETTINGS: '設定',
    SIGN_IN: '登入',
    SIGN_IN_ACTION: '登入',
    SIGN_IN_DESCRIPTION: '請輸入電子郵件與密碼登入',
    SIGN_IN_USERNAME_DESCRIPTION: '請輸入使用者名稱或電子郵件登入',
    SIGN_IN_WITH: 'Sign in with',
    SIGN_OUT: '登出',
    SIGN_UP: '註冊',
    SIGN_UP_ACTION: '建立帳戶',
    SIGN_UP_DESCRIPTION: '請填寫以下資料建立帳戶',
    SIGN_UP_EMAIL: '請到信箱確認驗證連結。',
    USERNAME: '使用者名稱',
    USERNAME_PLACEHOLDER: '使用者名稱',
    SIGN_IN_USERNAME_PLACEHOLDER: '使用者名稱或電子郵件',
    VERIFY_YOUR_EMAIL: '驗證您的電子郵件',
    VERIFY_YOUR_EMAIL_DESCRIPTION: '請確認您的電子郵件地址。請查看信箱中的驗證信，如果沒有收到，可以重新寄送。',
  },
  en: {
    SIGN_IN: 'Sign In',
    SIGN_IN_ACTION: 'Login',
    SIGN_IN_DESCRIPTION: 'Enter your email and password to login',
    SIGN_UP: 'Sign Up',
    SIGN_UP_ACTION: 'Create an account',
    SIGN_UP_DESCRIPTION: 'Enter your information to create an account',
  },
  ja: {
    ACCOUNT: 'アカウント',
    ADD_ACCOUNT: 'アカウントを追加',
    ALREADY_HAVE_AN_ACCOUNT: 'すでにアカウントをお持ちですか？',
    CANCEL: 'キャンセル',
    CONFIRM_PASSWORD: 'パスワード確認',
    CONFIRM_PASSWORD_PLACEHOLDER: 'パスワードを再入力',
    CONFIRM_PASSWORD_REQUIRED: '確認用パスワードを入力してください',
    CONTINUE: '続行',
    DONT_HAVE_AN_ACCOUNT: 'アカウントをお持ちでないですか？',
    EMAIL: 'メールアドレス',
    EMAIL_DESCRIPTION: 'ログインに使用するメールアドレスを入力してください。',
    EMAIL_INSTRUCTIONS: '有効なメールアドレスを入力してください。',
    EMAIL_PLACEHOLDER: 'name@example.com',
    EMAIL_REQUIRED: 'メールアドレスを入力してください',
    EMAIL_VERIFICATION: '確認リンクをメールでご確認ください。',
    FORGOT_PASSWORD: 'パスワードをお忘れですか',
    FORGOT_PASSWORD_ACTION: 'リセットリンクを送信',
    FORGOT_PASSWORD_DESCRIPTION: 'パスワードをリセットするメールアドレスを入力してください',
    FORGOT_PASSWORD_EMAIL: 'パスワードリセットリンクをメールでご確認ください。',
    FORGOT_PASSWORD_LINK: 'パスワードをお忘れですか？',
    GO_BACK: '戻る',
    IS_INVALID: 'が正しくありません',
    IS_REQUIRED: 'は必須です',
    NAME: '名前',
    NAME_DESCRIPTION: '氏名または表示名を入力してください。',
    NAME_INSTRUCTIONS: '最大32文字まで入力できます。',
    NAME_PLACEHOLDER: 'お名前',
    NEW_PASSWORD: '新しいパスワード',
    NEW_PASSWORD_PLACEHOLDER: '新しいパスワードを入力',
    NEW_PASSWORD_REQUIRED: '新しいパスワードを入力してください',
    OR_CONTINUE_WITH: 'または次の方法で続行',
    PASSWORD: 'パスワード',
    PASSWORD_PLACEHOLDER: 'パスワードを入力',
    PASSWORD_REQUIRED: 'パスワードを入力してください',
    PASSWORDS_DO_NOT_MATCH: 'パスワードが一致しません',
    PASSWORD_TOO_SHORT: 'パスワードが短すぎます',
    PASSWORD_TOO_LONG: 'パスワードが長すぎます',
    INVALID_EMAIL: 'メールアドレスの形式が正しくありません',
    INVALID_PASSWORD: 'パスワードの形式が正しくありません',
    INVALID_EMAIL_OR_PASSWORD: 'メールアドレスまたはパスワードが正しくありません',
    REMEMBER_ME: 'ログイン状態を保持',
    REQUEST_FAILED: 'リクエストに失敗しました。しばらくしてから再試行してください',
    RESET_PASSWORD: 'パスワードをリセット',
    RESET_PASSWORD_ACTION: '新しいパスワードを保存',
    RESET_PASSWORD_DESCRIPTION: '新しいパスワードを入力してください',
    RESET_PASSWORD_SUCCESS: 'パスワードをリセットしました',
    SAVE: '保存',
    SETTINGS: '設定',
    SIGN_IN: 'ログイン',
    SIGN_IN_ACTION: 'ログイン',
    SIGN_IN_DESCRIPTION: 'メールアドレスとパスワードを入力してログインしてください',
    SIGN_IN_USERNAME_DESCRIPTION: 'ユーザー名またはメールアドレスを入力してログインしてください',
    SIGN_IN_WITH: 'Sign in with',
    SIGN_OUT: 'ログアウト',
    SIGN_UP: '登録',
    SIGN_UP_ACTION: 'アカウントを作成',
    SIGN_UP_DESCRIPTION: 'アカウント作成に必要な情報を入力してください',
    SIGN_UP_EMAIL: '確認リンクをメールでご確認ください。',
    USERNAME: 'ユーザー名',
    USERNAME_PLACEHOLDER: 'ユーザー名',
    SIGN_IN_USERNAME_PLACEHOLDER: 'ユーザー名またはメールアドレス',
    VERIFY_YOUR_EMAIL: 'メールアドレスを確認',
    VERIFY_YOUR_EMAIL_DESCRIPTION: 'メールアドレスを確認してください。確認メールが届いていない場合は再送できます。',
  },
};

export function getNeonAuthLocalization(lang) {
  return neonAuthLocalizations[lang] || neonAuthLocalizations.en;
}
